---
title: "Assignment1_MA"
author: "Akshita"
date: "2024-02-11"
output: html_document
---

## R Markdown

Q1. Ask an important question you want answered (1 at least)

Ans:
1. What are the most common symptoms associated with lung cancer?
2. Which one are the most significant factors associated with the presence of lung cancer?
3. Is there any correlation of age with lung cancer?

Q2. Answer why this question(s) is/are important to you?

Ans: These questions are important as they can help in early detection so timely treatment can be done. Also, Understanding how age affects the risk of getting lung cancer helps doctors decide when and how often someone should be screened for the disease.

Q3. Find and collect data (need one dependent variable and more than 3 dependent variables)?

Ans: I have taken the dataset from kaggle.
https://www.kaggle.com/datasets/nancyalaswad90/lung-cancer

Q4. Describe your data (create a data dictionary)?

Ans. There are:

1 dependent variable- 

LUNG_CANCER (Target)
  
9 independent variables-
  
GENDER
AGE
SMOKING
WHEEZING
ALCOHOL CONSUMING
COUGHING
SHORTNESS OF BREATH
SWALLOWING DIFFICULTY
CHEST PAIN
  
Except age and gender, all the values in this dataset are given as 1 & 2 where 1 = "NO" and 2 = "YES". These are categorical values.

Description of the attributes:

GENDER: Gender of the patient.

AGE: Age of the patient.

SMOKING: Whether the patient smokes or not.

WHEEZING: Presence of wheezing.

ALCOHOL CONSUMING: Whether the patient 
consumes alcohol.

COUGHING: Presence of coughing.

SHORTNESS OF BREATH: If patient suffers from shortness of breath.

SWALLOWING DIFFICULTY: Difficulty in swallowing.

CHEST PAIN: Presence of chest pain.

LUNG CANCER: Presence of lung cancer in the patient.






